### ISSUE TITLE
[BUG] unable to recover connection after network loss

### ISSUE THREAD

**Issue by vbelloir** [b100dian/harbour-sailslack#2]
**Describe the bug**
Sailslack 1.4.7

when network connection (cellular or Wifi) is lost (because of lack of coverage or connection is simply switch off), sailslack don't work when connection is back.
User have to kill sailslack and reopen it to get it connected and work again.

**To Reproduce**
Is there a way to get sailslack logs?

**Expected behavior**
when connection is back, Sailslack should get connection ready immediately.

**Comment by b100dian** [comment]
Closed in favor of the upstream bug https://github.com/danvratil/harbour-sailslack/issues/26
