### ISSUE TITLE
[FEATURE REQUEST]Option of sort in channel list view

### ISSUE THREAD

**Issue by vbelloir** [b100dian/harbour-sailslack#4]
Since 1.4.6, starred channels and conversations are managed, but now, unread channels are not anymore on top.  

Is it possible to  get option of with filter should be used (unread, starred) or to get a mixte of it like this:

```
Starred
  * blabla1
  * blabla 2

Unread 
  * blabla 3
  * blabla 4

Channels
  * ...

Direct messages
  * ...  
```

**Comment by ncartron** [comment]
agreed, that would be wonderful :)

**Comment by b100dian** [comment]
This is not the case anymore in 1.4.7-8-9 and the Openrepos 0.2.
If we ever change the sorting order we will consider preferences for it, right now unreads are back on top.
(please use https://github.com/danvratil/harbour-sailslack/issues/ if you want to open another one),
Thanks!
